#output.logstash:
#  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT:5044}"]

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT:9200}"]

setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT:5601}"

setup.dashboards.enabled: true
