# https://github.com/elastic/logstash-docker
ARG TAG
FROM docker.elastic.co/logstash/logstash-oss:$TAG

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
