version: '3.5'

services:
  elasticsearch:
    container_name: elasticsearch_$ELASTIC_VERSION
    image: elasticsearch:$ELASTIC_VERSION
    build:
      context: elasticsearch/
      args:
        - ELASTIC_VERSION=$ELASTIC_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch-$ELASTIC_VERSION.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elastic 

      #  logstash:
#    container_name: ffknob_logstash
#    build:
#      context: logstash/
#      args:
#        - ELASTIC_VERSION=$ELASTIC_VERSION
#    volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
#    ports:
#      - "5000:5000"
#      - "5044:5044"
#    environment:
#      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
#    networks:
#      - elastic
#    depends_on:
#      - elasticsearch

  kibana:
    container_name: kibana_$ELASTIC_VERSION
    image: kibana:$ELASTIC_VERSION
    build:
      context: kibana/
      args:
        - ELASTIC_VERSION=$ELASTIC_VERSION
    volumes:
      - ./kibana/config/kibana-$ELASTIC_VERSION.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  apm-server:
    container_name: apm-server_$ELASTIC_VERSION
    image: apm-server:$ELASTIC_VERSION
    build:
      context: apm-server/
      args:
        - ELASTIC_VERSION=$ELASTIC_VERSION
    volumes:
      - ./apm-server/config/apm-server-$ELASTIC_VERSION.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - "8200:8200"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  # Métricas de serviços
#  metricbeat:
#    container_name: ffknob_metricbeat
#    build:
#      context: beats/metricbeat/
#      args:
#        - ELASTIC_VERSION=$ELASTIC_VERSION
#    environment:
#      - WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601
#      - ELASTICSEARCH_HOST=elasticsearch
#      - ELASTICSEARCH_PORT=9200
#      - LOGSTASH_HOST=logstash
#      - LOGSTASH_PORT=5044
#      - KIBANA_HOST=kibana
#      - KIBANA_PORT=5601
#    depends_on:
#      - logstash
#      - kibana
#    networks:
#      - elastic

  # Métricas do Docker host
  # Como não tem acesso à rede do Docker, acessa os serviços pelos IPs e portas expostos 
#  metricbeat-host:
#    container_name: ffknob_metricbeat-host
#    build:
#      context: beats/metricbeat/
#      args:
#        - ELASTIC_VERSION=$ELASTIC_VERSION
#    environment:
#      - WAIT_FOR_HOSTS=$ELASTICSEARCH_HOST:$ELASTICSEARCH_PORT $KIBANA_HOST:$KIBANA_PORT
#      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
#      - ELASTICSEARCH_PORT=$ELASTICSEARCH_PORT
#      - LOGSTASH_HOST=$LOGSTASH_HOST
#      - LOGSTASH_PORT=$LOGSTASH_PORT
#      - KIBANA_HOST=$KIBANA_HOST
#      - KIBANA_PORT=$KIBANA_PORT
#    volumes:
#      - ./beats/metricbeat/config/metricbeat-host.yml:/usr/share/metricbeat/metricbeat.yml:ro
#      - /proc:/hostfs/proc:ro
#      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#      - /:/hostfs:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#    network_mode: host    

# Métricas das aplicações
#  hb-portal-internet:
#   container_name: ffknob_hb-portal-internet
#   build: 
#     context: beats/heartbeat/
#     args:
#       - ELASTIC_VERSION=$ELASTIC_VERSION
#   environment:
#     - WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601
#     - ELASTICSEARCH_HOST=elasticsearch
#     - ELASTICSEARCH_PORT=9200
#     - LOGSTASH_HOST=logstash
#     - LOGSTASH_PORT=5044
#     - KIBANA_HOST=kibana
#     - KIBANA_PORT=5601
#   volumes:
#     - ./beats/heartbeat/heartbeats/portal-internet.yml:/usr/share/heartbeat/heartbeat.yml:ro
#   networks:
#     - elastic
#   depends_on:
#     - elasticsearch

networks:
  elastic:

volumes:
  elasticsearch_data:
    name: elasticsearch_data_$ELASTIC_VERSION
