version: "3.5"

services:
  elasticsearch_bootstrap:
    container_name: elasticsearch_bootstrap
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - node.name=elasticsearch_bootstrap
      - cluster.name=elasticsearch-cluster
      - network.host=_local_
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USER_PASSWORD=$ELASTIC_USER_PASSWORD
      - KIBANA_USER_PASSWORD=$KIBANA_USER_PASSWORD
      - LOGSTASH_SYSTEM_USER_PASSWORD=$LOGSTASH_SYSTEM_USER_PASSWORD
      - BEATS_SYSTEM_USER_PASSWORD=$BEATS_SYSTEM_USER_PASSWORD
      - APM_SYSTEM_USER_PASSWORD=$APM_SYSTEM_USER_PASSWORD
      - REMOTE_MONITORING_USER_PASSWORD=$REMOTE_MONITORING_USER_PASSWORD
      - CA_PASSWORD=$CA_PASSWORD
      - ELASTICSEARCH01_CERT_PASSWORD=$ELASTICSEARCH01_CERT_PASSWORD
      - ELASTICSEARCH02_CERT_PASSWORD=$ELASTICSEARCH02_CERT_PASSWORD
      - ELASTICSEARCH03_CERT_PASSWORD=$ELASTICSEARCH03_CERT_PASSWORD
      - KIBANA_CERT_PASSWORD=$KIBANA_CERT_PASSWORD
    command: >
      bash -c '
        if [[ ! -f /shared/certfificates.ready ]]; then
          echo "[Generating CA]"
          bin/elasticsearch-certutil ca --silent --pass ${CA_PASSWORD} --pem --out /certs/ca.zip
          unzip /certs/ca.zip -d /certs

          echo "[Generating certificate for Elasticsearch01]"
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --ca-pass ${CA_PASSWORD} --pass ${ELASTICSEARCH01_CERT_PASSWORD} --dns elasticsearch01 --out /certs/elasticsearch01.p12

          echo "[Generating certificate for Elasticsearch02]"
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --ca-pass ${CA_PASSWORD} --pass ${ELASTICSEARCH02_CERT_PASSWORD} --dns elasticsearch02 --out /certs/elasticsearch02.p12

          echo "[Generating certificate for Elasticsearch03]"
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --ca-pass ${CA_PASSWORD} --pass ${ELASTICSEARCH02_CERT_PASSWORD} --dns elasticsearch03 --out /certs/elasticsearch03.p12

          echo "[Generating certificate for Kibana]"
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --ca-pass ${CA_PASSWORD} --pass ${KIBANA_CERT_PASSWORD} --pem --dns kibana --out /certs/kibana.zip
          unzip /certs/kibana.zip -d /certs
          mv /certs/instance/instance.crt /certs/kibana.crt
          mv /certs/instance/instance.key /certs/kibana.key
          rm -rf /certs/instance

          chown -R 1000:0 /certs

          touch /shared/certificates.ready
      fi;

      if [[ ! -f /shared/built_in_users.ready ]]; then
          echo "[Bringing Elasticsearch up]"
          ./bin/elasticsearch -d -p pid

          curl -s -o /shared/elasticsearch_startup.status https://localhost:9200/_cluster/health\?filter_path\=timed_out\&timeout\=30s\&wait_for_nodes\=1 -k -u elastic:${ELASTIC_USER_PASSWORD}

          ELASTICSEARCH_STARTUP_TIMED_OUT=`cat /shared/elasticsearch_startup.status | grep true > /dev/null`
          if [[ ${ELASTICSEARCH_STARTUP_TIMED_OUT} -eq 0 ]]; then
            echo "Elasticsearch did not came up after 30 seconds. Aborting."
            exit -1
          fi

          echo "[Creating keystore]"
          ./bin/elasticsearch-keystore create

          echo "[Adding elastic user bootstrap password]"
          echo ${ELASTIC_USER_PASSWORD} | ./bin/elasticsearch-keystore add --stdin bootstrap.password

          echo "[Setting elastic user password]"
          curl -XPOST -H"Content-type: application/json" https://localhost:9200/_security/user/elastic/_password -k -u elastic:${ELASTIC_USER_PASSWORD} -d'{ "password": "'${ELASTIC_USER_PASSWORD}'"}'

          echo "[Setting kibana user password]"
          curl -XPOST -H"Content-type: application/json" https://localhost:9200/_security/user/kibana/_password -k -u elastic:${ELASTIC_USER_PASSWORD} -d'{ "password": "'${KIBANA_USER_PASSWORD}'"}'

          echo "[Setting logstash_system user password]"
          curl -XPOST -H"Content-type: application/json" https://localhost:9200/_security/user/logstash_system/_password -k -u elastic:${ELASTIC_USER_PASSWORD} -d'{ "password": "'${LOGSTASH_SYSTEM_USER_PASSWORD}'"}'

          echo "[Setting beats_system user password]"
          curl -XPOST -H"Content-type: application/json" https://localhost:9200/_security/user/beats_ystem/_password -k -u elastic:${ELASTIC_USER_PASSWORD} -d'{ "password": "'${BEATS_SYSTEM_USER_PASSWORD}'"}'

          echo "[Setting apm_system user password]"
          curl -XPOST -H"Content-type: application/json" https://localhost:9200/_security/user/apm_system/_password -k -u elastic:${ELASTIC_USER_PASSWORD} -d'{ "password": "'${APM_SYSTEM_USER_PASSWORD}'"}'

          echo "[Setting remote_monitoring_user user password]"
          curl -XPOST -H"Content-type: application/json" https://localhost:9200/_security/user/remote_monitoring_user/_password -k -u elastic:${ELASTIC_USER_PASSWORD} -d'{ "password": "'${REMOTE_MONITORING_USER_PASSWORD}'"}'

          echo "[Bringing Elasticsearch down]"
          kill -9 `cat pid`

          touch /shared/built_in_users.ready
        fi;

        touch /shared/bootstrap.ready

        sleep 600
      '
    working_dir: /usr/share/elasticsearch
    user: "0"
    volumes:
      - shared:/shared
      - certs:/certs
      - elasticsearch01_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD",
          "test",
          "-f",
          "/shared/certificates.ready",
          "-a",
          "-f",
          "/shared/built_in_users.ready",
          "-a",
          "-f",
          "/shared/bootstrap.ready"
        ]
      interval: 5s
      timeout: 10s
      retries: 10

  elasticsearch01:
    container_name: elasticsearch01_$ELASTIC_VERSION
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    volumes:
      - shared:/shared
      - certs:/usr/share/elasticsearch/config/certs/:ro
      - elasticsearch01_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
      - ELASTIC_USER_PASSWORD=$ELASTIC_USER_PASSWORD
      - node.name=elasticsearch01
      - cluster.name=elasticsearch-cluster
      - network.host=_site_
      - discovery.seed_hosts=elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.security.authc.realms.file.file1.order=0
      - xpack.security.authc.realms.native.native1.order=1
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.password=$ELASTICSEARCH01_CERT_PASSWORD
      - xpack.security.transport.ssl.truststore.password=$ELASTICSEARCH01_CERT_PASSWORD
      - xpack.security.transport.ssl.keystore.path=certs/elasticsearch01.p12
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.password=$ELASTICSEARCH01_CERT_PASSWORD
      - xpack.security.http.ssl.truststore.password=$ELASTICSEARCH01_CERT_PASSWORD
      - xpack.security.http.ssl.keystore.path=certs/elasticsearch01.p12
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    depends_on:
      - elasticsearch_bootstrap

  elasticsearch02:
    container_name: elasticsearch02_$ELASTIC_VERSION
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    volumes:
      - shared:/shared
      - certs:/usr/share/elasticsearch/config/certs/:ro
      - elasticsearch02_data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
      - ELASTIC_USER_PASSWORD=$ELASTIC_USER_PASSWORD
      - node.name=elasticsearch02
      - cluster.name=elasticsearch-cluster
      - network.host=_site_
      - discovery.seed_hosts=elasticsearch01,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.security.authc.realms.file.file1.order=0
      - xpack.security.authc.realms.native.native1.order=1
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.password=$ELASTICSEARCH02_CERT_PASSWORD
      - xpack.security.transport.ssl.truststore.password=$ELASTICSEARCH02_CERT_PASSWORD
      - xpack.security.transport.ssl.keystore.path=certs/elasticsearch01.p12
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.password=$ELASTICSEARCH02_CERT_PASSWORD
      - xpack.security.http.ssl.truststore.password=$ELASTICSEARCH02_CERT_PASSWORD
      - xpack.security.http.ssl.keystore.path=certs/elasticsearch01.p12
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    depends_on:
      - elasticsearch_bootstrap

  elasticsearch03:
    container_name: elasticsearch03_$ELASTIC_VERSION
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    volumes:
      - shared:/shared
      - certs:/usr/share/elasticsearch/config/certs/:ro
      - elasticsearch03_data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
      - ELASTIC_USER_PASSWORD=$ELASTIC_USER_PASSWORD
      - node.name=elasticsearch03
      - cluster.name=elasticsearch-cluster
      - network.host=_site_
      - discovery.seed_hosts=elasticsearch01,elasticsearch02
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.security.authc.realms.file.file1.order=0
      - xpack.security.authc.realms.native.native1.order=1
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.password=$ELASTICSEARCH03_CERT_PASSWORD
      - xpack.security.transport.ssl.truststore.password=$ELASTICSEARCH03_CERT_PASSWORD
      - xpack.security.transport.ssl.keystore.path=certs/elasticsearch01.p12
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.password=$ELASTICSEARCH03_CERT_PASSWORD
      - xpack.security.http.ssl.truststore.password=$ELASTICSEARCH03_CERT_PASSWORD
      - xpack.security.http.ssl.keystore.path=certs/elasticsearch01.p12
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    depends_on:
      - elasticsearch_bootstrap

  #  logstash:
  #    container_name: ffknob_logstash
  #    build:207a1f6ee79c
  #      context: logstash/
  #      args:
  #        - ELASTIC_VERSION=$ELASTIC_VERSION
  #    volumes:
  #      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #    ports:
  #      - "5000:5000"
  #      - "5044:5044"
  #    environment:
  #      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
  #    networks:
  #      - elastic
  #    depends_on:
  #      - elasticsearch01

  kibana:
    container_name: kibana_$ELASTIC_VERSION
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    volumes:
      - shared:/shared
      - certs:/usr/share/kibana/config/certs/:ro
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["https://elasticsearch01:9200","https://elasticsearch02:9200","https://elasticsearch03:9200"]
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=$KIBANA_USER_PASSWORD
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      #- SERVER_SSL_ENABLED=true
      #- SERVER_SSL_KEY=config/certs/kibana.key
      #- SERVER_SSL_CERTIFICATE=config/certs/kibana.crt
      #- SERVER_SSL_PASSWORD=$KIBANA_CERT_PASSWORD
      #- xpack.monitoring.elasticsearch.ssl.verificationMode=certificate
    networks:
      - elastic
    depends_on:
      - elasticsearch_bootstrap

#  apm-server:
#    container_name: apm-server_$ELASTIC_VERSION
#    image: docker.elastic.co/apm/apm-server:$ELASTIC_VERSION
#    volumes:
#      - ./apm-server/config/apm-server-$ELASTIC_VERSION.yml:/usr/share/apm-server/apm-server.yml:ro
#    ports:
#      - 8200:8200
#    environment:
#      apm-server.host: apm-server:8200
#      output.elasticsearch.hosts: elasticsearch01:9200
#    networks:
#      - elastic
#    depends_on:
#      - elasticsearch01

# Métricas de serviços
#  metricbeat:
#    container_name: ffknob_metricbeat
#    build:
#      context: beats/metricbeat/
#      args:
#        - ELASTIC_VERSION=$ELASTIC_VERSION
#    environment:
#      - WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601
#      - ELASTICSEARCH_HOST=elasticsearch
#      - ELASTICSEARCH_PORT=9200
#      - LOGSTASH_HOST=logstash
#      - LOGSTASH_PORT=5044
#      - KIBANA_HOST=kibana
#      - KIBANA_PORT=5601
#    depends_on:
#      - logstash
#      - kibana
#    networks:
#      - elastic

# Métricas do Docker host
# Como não tem acesso à rede do Docker, acessa os serviços pelos IPs e portas expostos
#  metricbeat-host:
#    container_name: ffknob_metricbeat-host
#    build:
#      context: beats/metricbeat/
#      args:
#        - ELASTIC_VERSION=$ELASTIC_VERSION
#    environment:
#      - WAIT_FOR_HOSTS=$ELASTICSEARCH_HOST:$ELASTICSEARCH_PORT $KIBANA_HOST:$KIBANA_PORT
#      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
#      - ELASTICSEARCH_PORT=$ELASTICSEARCH_PORT
#      - LOGSTASH_HOST=$LOGSTASH_HOST
#      - LOGSTASH_PORT=$LOGSTASH_PORT
#      - KIBANA_HOST=$KIBANA_HOST
#      - KIBANA_PORT=$KIBANA_PORT
#    volumes:
#      - ./beats/metricbeat/config/metricbeat-host.yml:/usr/share/metricbeat/metricbeat.yml:ro
#      - /proc:/hostfs/proc:ro
#      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#      - /:/hostfs:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#    network_mode: host

# Métricas das aplicações
#  hb-portal-internet:
#   container_name: ffknob_hb-portal-internet
#   build:
#     context: beats/heartbeat/
#     args:
#       - ELASTIC_VERSION=$ELASTIC_VERSION
#   environment:
#     - WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601
#     - ELASTICSEARCH_HOST=elasticsearch
#     - ELASTICSEARCH_PORT=9200
#     - LOGSTASH_HOST=logstash
#     - LOGSTASH_PORT=5044
#     - KIBANA_HOST=kibana
#     - KIBANA_PORT=5601
#   volumes:
#     - ./beats/heartbeat/heartbeats/portal-internet.yml:/usr/share/heartbeat/heartbeat.yml:ro
#   networks:
#     - elastic
#   depends_on:
#     - elasticsearch

#  app-search:
#    container_name: app-search_$ELASTIC_VERSION
#    image: app-search:$ELASTIC_VERSION
#    build:
#      context: app-search/
#      args:
#        - ELASTIC_VERSION=$ELASTIC_VERSION
#    volumes:
#      - ./app-search/config/app-search-$ELASTIC_VERSION.yml:/usr/share/app-search/app-search.yml:ro
#    environment:
#      - "JAVA_OPTS=-Xmx256m"
#    ports:
#      - 3002:3002
#    networks:
#      - elastic
#    depends_on:
#      - elasticsearch

networks:
  elastic:

volumes:
  shared:

  certs:

  elasticsearch01_data:
    name: elasticsearch01_data_$ELASTIC_VERSION

  elasticsearch02_data:
    name: elasticsearch02_data_$ELASTIC_VERSION

  elasticsearch03_data:
    name: elasticsearch03_data_$ELASTIC_VERSION
