# https://github.com/elastic/elasticsearch-docker
ARG TAG
FROM docker.elastic.co/beats/filebeat:$TAG

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
