version: '3'

services:

  elasticsearch:
    container_name: tcers_elasticsearch
    build:
      context: elasticsearch/
      args:
        - ELK_VERSION=$ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    container_name: tcers_logstash
    build:
      context: logstash/
      args:
        - ELK_VERSION=$ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        - ELK_VERSION=$ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  metricbeat:
    build:
      context: beats/metricbeat/
    command: -e
    environment:
      - LOGSTASH_HOST=$LOGSTASH_HOST
      - LOGSTASH_PORT=$LOGSTASH_PORT
      - KIBANA_HOST=$KIBANA_HOST
      - KIBANA_PORT=$KIBANA_PORT
    depends_on:
      - logstash
      - kibana
    networks:
      - elk

  metricbeat-host:
    build:
      context: beats/metricbeat/
      args:
        - ELK_VERSION=$ELK_VERSION
    environment:
      - LOGSTASH_HOST=$LOGSTASH_HOST
      - LOGSTASH_PORT=$LOGSTASH_PORT
      - KIBANA_HOST=$KIBANA_HOST
      - KIBANA_PORT=$KIBANA_PORT
    volumes:
      - ./beats/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host    

networks:

  elk:
    driver: bridge
